// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClK-xrRuOfFUC_rt6yQqXNWi9wRm9lKfo',
    appId: '1:901407158387:web:88238deae09c7fe983fa06',
    messagingSenderId: '901407158387',
    projectId: 'splitit-30119211',
    authDomain: 'splitit-30119211.firebaseapp.com',
    storageBucket: 'splitit-30119211.firebasestorage.app',
    measurementId: 'G-KK754BTMWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv4iqfz-yNXWwFwioyVUOzsVlICfvICXs',
    appId: '1:901407158387:android:5d9cbb18e9ba6dfa83fa06',
    messagingSenderId: '901407158387',
    projectId: 'splitit-30119211',
    storageBucket: 'splitit-30119211.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpqZqAPudDWqsOVTXuzHN8zpbw8bRCN1I',
    appId: '1:901407158387:ios:b26188be095b34f783fa06',
    messagingSenderId: '901407158387',
    projectId: 'splitit-30119211',
    storageBucket: 'splitit-30119211.firebasestorage.app',
    iosClientId: '901407158387-1g3lpdbsbcj7fqqljlpdh7cu5fgm3ak4.apps.googleusercontent.com',
    iosBundleId: 'com.splitit.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpqZqAPudDWqsOVTXuzHN8zpbw8bRCN1I',
    appId: '1:901407158387:ios:b26188be095b34f783fa06',
    messagingSenderId: '901407158387',
    projectId: 'splitit-30119211',
    storageBucket: 'splitit-30119211.firebasestorage.app',
    iosClientId: '901407158387-1g3lpdbsbcj7fqqljlpdh7cu5fgm3ak4.apps.googleusercontent.com',
    iosBundleId: 'com.splitit.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClK-xrRuOfFUC_rt6yQqXNWi9wRm9lKfo',
    appId: '1:901407158387:web:d6a1fdfb4800213483fa06',
    messagingSenderId: '901407158387',
    projectId: 'splitit-30119211',
    authDomain: 'splitit-30119211.firebaseapp.com',
    storageBucket: 'splitit-30119211.firebasestorage.app',
    measurementId: 'G-66QD4QXC9C',
  );

}